export const cardStats = [
    {
        level: 1,
        name: "Alpha",
        health: 5,
        attack: 2,
        defence: 1,
        speed: 1,
        critRate: 5,
        critDamage: 120,
        evasion: 1,
        accuracy: 100,
        cooldownReduction: 0,
        currentXp: 0,
        levelupXp: 100,
    },
    {
        level: 1,
        name: "Saya",
        health: 25,
        attack: 10,
        defence: 10,
        speed: 5,
        critRate: 15,
        critDamage: 150,
        evasion: 10,
        accuracy: 100,
        cooldownReduction: 0,
        currentXp: 0,
        levelupXp: 100,
    },
];